name: forex_replay_backtester
description: Offline CSV Forex Replay Backtesting App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.0.6
  csv: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
